version: '3.8'

services:
  web:
    build: .
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=transcribed_data

  etl:
    build: .
    command: ["sh", "-c", "sleep 10 && python etl_script.py"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web

volumes:
  postgres_data:
